### ISSUE TITLE
I am happy to work on this and collaborate

### ISSUE THREAD

**Issue by oberblastmeister** [tjdevries/rofl.nvim#2]
This seems really cool and rust is one of my favorite languages. I have worked on it a bit [here](https://github.com/oberblastmeister/rofl.nvim).

**Comment by tjdevries** [comment]
I'll probably ask some questions over here: https://github.com/tjdevries/rofl.nvim/discussions/5

Happy to have more collaborators and talk about it a bit more. I see some of the things you're doing there, but I have a few other ideas about stuff I want to do as well I think. I have been bouncing ideas in my head and I'll write them down in discussions at some point.
